### ISSUE TITLE
Could not unmarshal json: json: can not unmarshal string into Go value of type [] string

### ISSUE THREAD

**Issue by jsianard** [jangaraj/serviced-app-zenoss5-network-weathermap#1]
i am trying to install the template "serviced-app-zenoss5-network-weathermap"
But the following answer when I issue the command serviced template add Application-Template-zenoss5-network-weathermap.json:
"Could not unmarshal json: json: can not unmarshal string into Go value of type [] string"

**Comment by jangaraj** [comment]
This is not supported project. Code is published only for inspiration.
